# Pre-commit hooks configuration
# Install: pip install pre-commit
# Setup: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: make fmt
        language: system
        files: \.go$
        pass_filenames: false

      - id: go-vet
        name: go vet
        entry: make vet
        language: system
        files: \.go$
        pass_filenames: false

      - id: go-test
        name: go test
        entry: make test
        language: system
        files: \.go$
        pass_filenames: false
        stages: [push]

