name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    name: Test (Go ${{ matrix.go-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: ['1.23', '1.24']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Install Bitcoin Core
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          # Use snap for reliable installation across Ubuntu versions
          sudo snap install bitcoin-core
          # Create symlinks for standard paths
          sudo ln -sf /snap/bitcoin-core/current/bin/bitcoind /usr/local/bin/bitcoind
          sudo ln -sf /snap/bitcoin-core/current/bin/bitcoin-cli /usr/local/bin/bitcoin-cli
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install bitcoin
        fi
      shell: bash

    - name: Verify Bitcoin Core installation
      run: |
        which bitcoind
        bitcoind --version

    - name: Install development tools
      run: make install-tools

    - name: Run CI checks
      run: make ci

    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.go-version == '1.23'
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-${{ matrix.os }}-go${{ matrix.go-version }}
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}

